### ISSUE TITLE
 js 、reversion 会把js内变量的值 误改，是不是正则没做好匹配啊。

### ISSUE THREAD

**Issue by ipengyo** [weixin/tmt-workflow#100]
情况： 我在index.js文件中 定义了一个变量 var foo = 'index';

经过tmt的 reversion流程后。。
我发现build出来的index.js 文件内 变量值 被该成了  var foo = 'index.e6412556'

后面多了一个md值，这是为啥。。。

导致异常，后来我就得改名字了。

**Comment by hzlzh** [comment]
看这里：https://github.com/weixin/tmt-workflow/wiki/%E2%92%96-Reversion-%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88
这个是为了去除浏览器缓存的 md5 新文件名方案
