### ISSUE TITLE
一直停在running界面

### ISSUE THREAD

**Issue by wancongji** [weixin/tmt-workflow#102]
之前大约一周都使用正常，今天使用的时候突然就出现保存的时候，页面没有自动更新，之后就无法正常监听，一直处在running状态

**Comment by wancongji** [comment]
![image](https://cloud.githubusercontent.com/assets/25276660/25326518/289a6dec-2903-11e7-8ddc-06e5cc2225a1.png)

**Comment by wancongji** [comment]
![image](https://cloud.githubusercontent.com/assets/25276660/25326555/4b9f36a6-2903-11e7-8f4c-f9a977fc66f4.png)

**Comment by wancongji** [comment]
一直卡在这个页面，无法进入开发模式

**Comment by hzlzh** [comment]
是不是有语法错误导致，默认 example 能正常跑起来么？

**Comment by wancongji** [comment]
嗯，是语法错误，已解决
