### ISSUE TITLE
It's really weired when run npm install!

### ISSUE THREAD

**Issue by Troland** [weixin/tmt-workflow#104]
Hi, there's a problem that when i execute the command `npm install` to install the packages after clone the repo locally.It always suck in the following problem:

<img width="490" alt="tmt-workflow-error" src="https://cloud.githubusercontent.com/assets/1475173/25397051/81c90dd0-2a19-11e7-9913-2da0a8b7d9a1.png">

Any clues?My node version is *6.0.0*,npm version is *3.8.6*, My system is mac os *10.12.4*.

**Comment by hzlzh** [comment]
Try switch node to v4.4.0 with tools like [n](https://github.com/tj/n) and `npm install` again.
I got the same OSX version like yours.

**Comment by Troland** [comment]
@hzlzh thanks for your methods, through it failed on *4.4.0*, i try on *6.8.0* and then it works.
