### ISSUE TITLE
提示安装失败  UNMET PEER DEPENDENCY yo@>=1.0.0

### ISSUE THREAD

**Issue by CGerAJ** [weixin/tmt-workflow#106]
`C:\Users\Administrator>npm install -g generator-workflow
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@0.9.15: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
E:\Program Files\nodejs\node_glabal
+-- generator-workflow@1.4.3
`-- UNMET PEER DEPENDENCY yo@>=1.0.0

npm WARN generator-workflow@1.4.3 requires a peer of yo@>=1.0.0 but none was installed.`

提示安装失败 没找到失败原因~

**Comment by CGerAJ** [comment]
不是初始化项目 我重新安装了操作系统  使用gulp4.0 安装模块 提示找不到模块
`D:\phpStudy\WWW\tmt-workflow>npm install
npm WARN enoent ENOENT: no such file or directory, open 'D:\phpStudy\WWW\tmt-workflow\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'D:\phpStudy\WWW\tmt-workflow\node_modules\vinyl-fs\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'D:\phpStudy\WWW\tmt-workflow\node_modules\vinyl-fs\node_modules\minimist\package.json'
npm WARN tmt-workflow No description
npm WARN tmt-workflow No repository field.
npm WARN tmt-workflow No README data
npm WARN tmt-workflow No license field.
`

**Comment by CGerAJ** [comment]
非初始化项目 我应该如何配置

**Comment by soyaine** [comment]
hello 这个问题是怎么解决的?

**Comment by hzlzh** [comment]
@soyaine so
你遇到什么报错了？可以发来看看

**Comment by soyaine** [comment]
@hzlzh 多谢，我翻了翻其他 issue 解决了。
重新下载 yo，把 node 版本调低，然后根据运行后提示错误的包重新下了一遍。
最后跑通了。
