### ISSUE TITLE
dist命令下Autoprefixer没有补全，反而会删除-webkit浏览器私有属性?

### ISSUE THREAD

**Issue by memoryofchild** [weixin/tmt-workflow#109]
最近在发现了个问题，就是工作流在dev的时候使用自带的lib-mixins可以补全浏览器私有属性，但是在dist的时候，跑了compileAutoprefixer任务后，发现反而把私有属性给删除了。

我是这么测试的，把TaskBuildDist里的miniCSS任务注释掉，然后将dev出来的css和dist出来的css做文件对比发现的。

是不是我哪里配置的不对？

如下图：
![Markdown](http://i4.piimg.com/1949/baf3698df13dd55b.jpg)

**Comment by littledu** [comment]
https://github.com/weixin/tmt-workflow/blob/master/_tasks/TaskBuildDist.js#L91

你可以把这一行的 `last 5 versions` 改大，兼容更多版本的浏览器，比如 `last 99 version`。试试

**Comment by memoryofchild** [comment]
问题解决了：）感谢，不过不知道是啥问题，估计是我的chrome版本问题吧：版本 58.0.3029.110 (64-bit)（应该没有超过last 5 versions哈哈）

**Comment by littledu** [comment]
上条回复的时候没看到你的截图，实际上你这个 -webkit-border-radius 是不需要前缀的了，但 Autoprefixer 帮我们优化了有人觉得好有人觉得不好，它是以最近的x个版本来作为判断的，如果想兼容多一点版本，就把数值设得大大的就好了，以chrome的更新速度，很快就都过期了。
