### ISSUE TITLE
为什么没有对img目录的图片进行retina媒体查询的输出？

### ISSUE THREAD

**Issue by Troland** [weixin/tmt-workflow#110]
我有个疑问感觉不理解，我看到用了*gulp-tmtsprite*有对slice里面的图片进行图片的合并和@2x,@3x媒体查询.可是为什么没有对img目录下的图片文件不也得添加那个@2x,@3x的媒体查询的设置吗？因为这个img文件如果retina下是需要2倍图片的不是吗？

**Comment by littledu** [comment]
img 目录的定义会偏向于放一些较大不适合合并的图片，这种图片一般就是一些大背景图或者演示需要的内容图，内容图一般用的 img 标签来引用，后续会被实际图片替换，大背景图处理的话比较耗时，这是原因。

实际上，目前基本都是 retina 屏幕了，雪碧图的生成代码可以废弃掉兼容代码了，后续可以优化一下。

**Comment by Troland** [comment]
@littledu 多谢，就是那个1倍的图可以丢掉了吧。不过，我这里用那个sprite出现了很奇怪的事情。就是那个构建出来@2x的图出现了问题比如，请看以下两个@2x的图：
图1:
<img width="126" alt="bug2" src="https://user-images.githubusercontent.com/1475173/27192161-e0d2b610-522c-11e7-81a5-bb33be96b21b.png">
图2:
<img width="92" alt="bug" src="https://user-images.githubusercontent.com/1475173/27192169-e8da0b6a-522c-11e7-8f8a-f944e4f6c52f.png">

不知道为什么图2的那个图偏向右边，结果导致那个在页面上显示会有缺失.
如图:
<img width="81" alt="bug3" src="https://user-images.githubusercontent.com/1475173/27192372-adb1d36e-522d-11e7-820b-76bc306c63de.png">

以上是我在iphone5上看到的，然后如果拿到android机上的会显示得更加明显，那个右边会缺一块。
这边感觉非常的不理解

**Comment by littledu** [comment]
看是否开启了 rem，rem 不太适合使用雪碧图

**Comment by Troland** [comment]
@littledu 开启了,呃。应该是要换flexible了吧。

**Comment by Troland** [comment]
非常感谢，我明天用flexible,感谢您耐心回答。

**Comment by littledu** [comment]
你也可以选择把所有图片都放 img ，不用雪碧图功能

**Comment by Troland** [comment]
你好，感谢回答，我也是整理到了img目录然后有的图标是用的背景图引用的img目录下的，这个时候是需要添加那个高清图片的媒体查询吧。因为都是些小图标吧。

**Comment by littledu** [comment]
直接上二倍图了，也就不用写媒体查询了，现在基本的设备都是高清屏了。

**Comment by Troland** [comment]
三倍图得写呢
