### ISSUE TITLE
yeoman的是老版本基于grunt?

### ISSUE THREAD

**Issue by ah-kevin** [weixin/tmt-workflow#12]
我看了下yo生存的是grunt的 这个gulp的还没有generator 吧

**Comment by Loyalsoldier** [comment]
我也希望这个新的 Workflow 尽快出 Yeoman Generator 哈哈~~

**Comment by littledu** [comment]
@ah-kevin @Loyalsoldier 欢迎提 Pull requests

**Comment by hzlzh** [comment]
@ah-kevin 是的旧版流程是基于 Grunt 的，已经淘汰，拥抱 Gulp 吧。 cc @Loyalsoldier 

`yo tmt` enjoy~
https://github.com/weixin/generator-tmt
