### ISSUE TITLE
rem字体

### ISSUE THREAD

**Issue by ah-kevin** [weixin/tmt-workflow#13]
rem的字体解决也是rem么 还是不同的dpr下不同的PX~~

**Comment by hzlzh** [comment]
是的，所有 CSS 属性值在编写时使用 `px` 作为单位，最终经过工作流会自动转换成 `rem` 单位。
更多 rem 文档可参看 [这里 WiKi](https://github.com/weixin/tmt-workflow/wiki/%E2%92%94-REM-%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88)

**Comment by ah-kevin** [comment]
哦  字体大小是rem的号 好像个别机子上面显示的有问题~~

**Comment by hzlzh** [comment]
有没有页面和重现方式，发来看一下

**Comment by ah-kevin** [comment]
因为我一直用的是淘宝的方案~~很好用的!不是用media screen去控制html的font-size;
链接:https://github.com/amfe/lib-flexible

**Comment by hzlzh** [comment]
所以是混用了两种方案造成的么？
TB 的方案要引入 js，你是试一下去除那条 js，然后引入 [lib-rem.less](https://github.com/weixin/tmt-workflow/blob/master/project/src/css/lib-rem.less) 试试

**Comment by ah-kevin** [comment]
好的 !知道了 !这个可以关闭了 3q!
