### ISSUE TITLE
TmTIndex.html页面生成二维码有问题

### ISSUE THREAD

**Issue by xiewl** [weixin/tmt-workflow#14]
new QRCode(document.getElementById("qrcode"), encodeURI(window.location.href+$(this).parent().parent().find("a").text()))
错误生成格式：http://localhost:8080/html/TmTIndex.htmlwelcome.html
我这边的临时解决方案，通过host+a标签的href属性重新拼接。
new QRCode(document.getElementById("qrcode"), encodeURI("http://"+location.host+ "/html/" + $(this).parent().parent().find("a").attr("href")));});

**Comment by littledu** [comment]
@xiewl  谢谢反馈，已修复
