### ISSUE TITLE
有没有类似 gulp serve:dist 方法可以 预览本地DIST目录

### ISSUE THREAD

**Issue by iamike** [weixin/tmt-workflow#17]
请问我想在本地测试最终的DIST环境，有没有TASK可以直接的方法而不用我FTP到服务器上就能测

**Comment by hzlzh** [comment]
`gulp build_dist` 不就是干这个的？

**Comment by iamike** [comment]
我是想直接跳出来 弹出来一个窗口，127.0.0.1:8080/但是内容不是dev的了，而是dist的了

**Comment by hzlzh** [comment]
你可以自己定制一个新的 task，执行完 dist 以后 `watch` `startServer` 即可。

**Comment by iamike** [comment]
恩，好
