### ISSUE TITLE
gulp dist 的JS 能否剔除 js concatenate的minify 文件 

### ISSUE THREAD

**Issue by iamike** [weixin/tmt-workflow#18]
![eb1c87c4-0c38-4f91-b588-bef9dea60a19](https://cloud.githubusercontent.com/assets/526854/14421162/a300d70e-0002-11e6-8577-ee075db33b50.png)

**Comment by hzlzh** [comment]
`js: './src/js/**/*.{js,!min.js}',`
https://github.com/weixin/tmt-workflow/blob/master/_tasks/TaskBuildDist.js#L31

**Comment by iamike** [comment]
那能不能不生成出来其他红色框的文件，因为已经合并到lib中了。

**Comment by hzlzh** [comment]
这个需要你定制一下，类似 `miniCSS `
