### ISSUE TITLE
设计稿中的字体大小都是使用 pt（点）作为单位的，编码过程中如何转换成 px？

### ISSUE THREAD

**Issue by Loyalsoldier** [weixin/tmt-workflow#19]
如题。

**Comment by littledu** [comment]
![image](https://cloud.githubusercontent.com/assets/1784673/14597797/8d3507cc-0581-11e6-99d6-c1a013eea0d0.png)

打开 PS-> 首选项->单位与标尺，选择 `像素`, 这样，你在设计稿中看到的就是 px，不用去编码转换。

**Comment by Loyalsoldier** [comment]
谢谢！

我发现好像 1pt 对应 1px，iPhone 6 的设计稿。
