### ISSUE TITLE
这个 Workflow 支持 EJS 模板引擎，可为什么 Task 里面编译 HTML 的代码里没有转换 .ejs 格式为 .html 格式的步骤？

### ISSUE THREAD

**Issue by Loyalsoldier** [weixin/tmt-workflow#21]
我没用过 EJS 模板引擎，但以往用其他模板引擎的经验告诉我，模板应该都有自己特殊的格式，例如 Handlebars 的文件后缀为 .hbs。

既然本 Workflow 是支持 EJS 模板引擎的，为什么在 Task 里面编译 HTML 的代码部分没有转换 .ejs 格式文件为 .html 的步骤？

https://github.com/weixin/tmt-workflow/blob/master/_tasks/TaskBuildDev.js#L99-L118

BTW，我用 EJS 模板主要是为了快速引入 CSS 和 JS 而已……麻烦告知一下正确的用法。

**Comment by littledu** [comment]
模版引擎一般都有自己的后缀格式，但也没有规定就只能加载它的后缀格式的文件，模版引擎都是服务于 html 文件，所以，几乎所有的模版引擎都是支持直接加载 .html 的。

在 WIKI 里面有详细的说明如何快速引入 CSS 和 JS 哦： https://github.com/weixin/tmt-workflow/wiki/%E2%92%90-EJS-%E6%A8%A1%E7%89%88%E8%AF%AD%E8%A8%80#css

**Comment by Loyalsoldier** [comment]
谢谢！
