### ISSUE TITLE
在 src 下的 html 目录里，不支持再新建子目录放置 html 文件？

### ISSUE THREAD

**Issue by Loyalsoldier** [weixin/tmt-workflow#22]
如题。

好像在 `html` 目录里再新建子目录，子目录里放置 `html` 文件后，用 EJS 模板引擎快速引入 CSS，运行 `gulp build_dev` 后，CSS 路径层级貌似解析不正确，少了几个层级……

**Comment by hzlzh** [comment]
支持的，子目录里层级试试 `../../css/`写法

**Comment by Loyalsoldier** [comment]
喔……还以为是自动判断目录层级的呢
