### ISSUE TITLE
建议支持 JS 模块化

### ISSUE THREAD

**Issue by Loyalsoldier** [weixin/tmt-workflow#23]
建议新增对 JS 模块化的支持。使用 ES2015 或者 Require.js 之类。像 REM 一样，在初始化 Workflow 时可选。

**Comment by littledu** [comment]
准备增加对 browserify 的支持

**Comment by Loyalsoldier** [comment]
期待！

**Comment by xyyjk** [comment]
建议增加 webpack + babel，可配性更强些

**Comment by littledu** [comment]
已在计划当中
