### ISSUE TITLE
如何进行组件化开发？

### ISSUE THREAD

**Issue by ouzhou** [weixin/tmt-workflow#25]
![r77c k r 7570u gkf__l p](https://cloud.githubusercontent.com/assets/7693866/15242650/fb3ccb0e-1929-11e6-8a83-02bc460d5127.png)

假如我这里写了一个header组件，它有js less 和html结构， 我想在index.html来include它,我希望gulp能帮我把less文件编译到/dev/css/common/header.css，然后动态吧这个css加载到head标签里面。这样开发是否正确？

**Comment by littledu** [comment]
你这个结构跟我们相差还比较大，需要自己定制一下，比如把组件直接用 ejs include 进去

**Comment by ouzhou** [comment]
![a 6fme m 2 8f e gohui5](https://cloud.githubusercontent.com/assets/7693866/15249585/e082ad82-1952-11e6-9bde-3ccad2d53b52.png)
想了一下我改结构太麻烦了就改成这样了。我发现在TaskBuildDev.js里面的less的src改成less: './src/css/**/style-*.less'这样会不会好一些，毕竟下面的lessAll也是这样写的

**Comment by littledu** [comment]
嗯，这里是个优化点，如果直接这样改有个 bug，编译好后的 css 文件现在是直接扔在 dev/dist 下面的 css 第一级目录下

**Comment by Loyalsoldier** [comment]
组件化开发和现在 TmT-workflow 的结构貌似有点违背。这也是 Workflow 会面临的很麻烦的一个问题：到底开源这个项目，是为了尽量满足社区的需求，还是只是提供给与自己项目和开发思路相似的开发者……我觉得这是一个值得思考的问题。

BTW，TmT-workflow 在 H5 的开发上确实是很棒的一个 workflow~~

**Comment by ouzhou** [comment]
其实_满足社区的需求_  跟 _只是提供给与自己项目和开发思路相似的开发者_ 这两个之间并不矛盾。工具的作用只是为了更好的生产。 更好的解决方法是 工具开发者只提供自己开发的_项目结构思路_，社区肯定会有其他的使用♂技巧♂，这个时候让他们自己提供其他方式比如模块化开发思路的**配置**给其他有相似需求的人参考，而不是让这个工具跟随改变。当然 **首先应该在文档中标明工具团队最推荐的方式**。

**Comment by littledu** [comment]
这一套流程是我们工作上的实践产出，我们应用得很不错，故开源出来，方便大家参考，交流，同时也能促进我们进一步完善，共同进步。
每个团队都有自己的习惯和开发方式，想要一个完全满足所有需求的工具是不太现实的，所以只能尽可能的“通用”，最好是能够方便“扩展”，所以我们在 readme 里第一句描述就提到 “扩展性”。我想还是挺方便扩展的。
不敢求满足所有的需求，只希望 tmt-workflow 能够对大家有帮助。
