### ISSUE TITLE
build_dev

### ISSUE THREAD

**Issue by dengxiaozhen** [weixin/tmt-workflow#26]
build_dev这个任务要自己写的吗

**Comment by littledu** [comment]
不用啊，直接执行 `gulp build_dev` 即可

**Comment by dengxiaozhen** [comment]
@littledu 提示没有这个任务

**Comment by dengxiaozhen** [comment]
![qq 20160517132506](https://cloud.githubusercontent.com/assets/8529528/15312024/1e166ba6-1c33-11e6-8d1a-1a6a3b97f36b.jpg)

**Comment by littledu** [comment]
你的 tasks 目录放在哪一级目录下，目录只支持 3 级，也就是说，最高只能放在跟 test 同级的目录

**Comment by dengxiaozhen** [comment]
@littledu 目录结构是这样的
![qq 20160517133039](https://cloud.githubusercontent.com/assets/8529528/15312103/d7bd3a08-1c33-11e6-8cbe-d8e3a56cf706.jpg)

**Comment by littledu** [comment]
结构是对的，你是不是用的 gulp3 ？这里需要 gulp4, 并且你在 webstorm 里面要设置对路径，比如这样：
![image](https://cloud.githubusercontent.com/assets/1784673/15312166/6227477e-1c34-11e6-9d85-136c5b418eb1.png)

**Comment by dengxiaozhen** [comment]
我用的 yeoman

**Comment by littledu** [comment]
专门跑了一下 yo, 没有问题，你这里如果跑不成功，怎么会有 dev 这个目录？

**Comment by dengxiaozhen** [comment]
我又重新执行了 gulp build_dev 能够执行了，但是 不会编译less或者scss

**Comment by littledu** [comment]
src 是源文件目录， 放的是 less 文件，`gulp build_dev` 编译后的文件在 dev 目录，你不用管，你只管在 src 目录下开发工作，他会自动监听并编译同步到 dev 那里去，完成后执行 `gulp build_dist` ，你可以花一点时间看一下文档

**Comment by dengxiaozhen** [comment]
好的 多谢指点
