### ISSUE TITLE
iphone 5适配

### ISSUE THREAD

**Issue by dericgit** [weixin/tmt-workflow#27]
// 21.33333333 = 320*20/375 (iPhone 5)
@media only screen and (min-width: 320px) {
    html {
        font-size: 19PX !important;
    }
}

// 17.06 = 320*20/375 (iPhone 5)
这个地方应该为17吧

**Comment by hzlzh** [comment]
* `21.33333333` 这个是复制时的笔误，注释里已修正为`17.06`。
* `19PX` 这里是一个 hack 写法，如果严格按照正常比例计算后是 `17.06`，但此时会出现  `9px 10px` 等中文小字缩放后识别度变差的问题，考虑到页面书写时本身具有响应式布局的特点，设置了 `19PX` 这个缩放比例比较合适。所以，如果是普通活动页面或者没有使用小字体可以考虑改回 `17.06` 的缩放基数。
