### ISSUE TITLE
雪碧图压缩找不到文件

### ISSUE THREAD

**Issue by ouzhou** [weixin/tmt-workflow#28]
![w mi w0fxsg6 _ p 9z6](https://cloud.githubusercontent.com/assets/7693866/15392293/c09d1926-1df8-11e6-91f0-0efae2625a94.png)
如图 在common里面的less有使用背景图片，dev都是正常的，但是dist就会告知找不到图片，原因是少找了一个层级，如何解决
![mv0n_j arpkvw vry a2 g](https://cloud.githubusercontent.com/assets/7693866/15392354/2fca23fc-1df9-11e6-95d4-853b637ad21f.png)

**Comment by littledu** [comment]
这个问题跟我们的规定有关，我们认为所有文件都是模块，都是可以公用的，所以不需要分目录存放，如果你觉得不好区分，可以适当用前缀来统一，比如库文件以 lib- 为前缀， ui 类用 ui- 比较纠结，以此类推可以有 commom- ，base- 等。

**Comment by ouzhou** [comment]
还有一个小的建议  加一些代码检查的东西比如jshint  或者代码风格jscs怎么样

**Comment by littledu** [comment]
嗯，后面考虑加一下，毕竟会让流程显得更完整。我们都使用 webstorm 作为主编辑器，比较强大，基本上一出错就会有相应提示，所以对我们来说 jshint 等就不是特别必要。

**Comment by littledu** [comment]
你是不是修改了 build_dist 的 less 的出口文件？要不然是不会去获取到二级目录下面的 style-*.less 的，理论来讲我们 css 的出口文件都在一级目录，二级目录你想放一些公用的模块也是可以的，雪碧图是没有问题的，只要你把 style-header.less -> header.less， 然后在需要这一个模块的 style-*.less 里面 @import 'commom/header' 即可
