### ISSUE TITLE
能贴一个开发目录吗？

### ISSUE THREAD

**Issue by ouzhou** [weixin/tmt-workflow#30]
![ea xk _ 45 5_i wwqhi](https://cloud.githubusercontent.com/assets/7693866/15447710/79979ed0-1f7d-11e6-80f9-f678111cd5da.png)
强行把文件夹去掉后，我感觉。。很难受。后面的各种组件都不知道该怎么命名了

**Comment by littledu** [comment]
我们不是有提供一个 project 吗？你也可以按你之前的目录，就是 css 目录下有个 commom 什么的
