### ISSUE TITLE
TaskBuildDev.js发现监视任务的BUG和win路径BUG

### ISSUE THREAD

**Issue by ktangel** [weixin/tmt-workflow#31]
两个BUG都在watchHandler 这个回调函数中，对监视任务的removed和add动作操作上有两个问题：
1， 201行的util.loadPlugin('BuildDev');这个方法是载入配置文件中定义的发布后要输入的插件，但你传入的字距和你的.tmtworkflowrc文件中的字串明显不一样，所以这个函数会执行不能。
2，file.replace('src/', 'dev/'); 这个方法只能用在mac等liunx系统下，在windows系统中，你这个已经不是在流中了，回调返回的路径的分隔斜杠是"\",而不是“/"，所以这个路径是不会切换成开发目录下的路径！
以上两个BUG最终会导致不管是win和liunx下，当文件被删除或是文件名被修改，开发环境的文件是不会有任何刷新。。
然后强烈建议把配置文件开放，不要弄这么个东西，既然开源，为什么要把配置文件搞得这么麻烦，比如直接读写在项目目录下的config.json什么的多好，这样就能根据不同项目进行定制插件和流程，又能共享插件和你的方法。
![image](https://cloud.githubusercontent.com/assets/11548772/15798767/d49020b0-2a76-11e6-8413-d3d8b2254ba9.png)
顺便再帖上我做的修正；
```
var watchHandler = function(type, file) {
		var target = file.match(/^src[\/|\\](.*?)[\/|\\]/)[1];
		var pathSrc = file.match(/^src[\/|\\]/)[0],
			pathDev;
		if (pathSrc === 'src/') {
			pathDev = 'dev/';
		} else if (pathSrc === 'src\\') {
			pathDev = 'dev\\';
		}else{
			throw(pathSrc + "根路径出错");
		};
		var tmp = file.replace(pathSrc, pathDev);
		switch (target) {
```
然后对是下面的调用错误的修正以html文件为例：
```
case 'html':
				if (type === 'removed') {
					del([tmp]).then(function() {
						util.loadPlugin('build_dev');
					})
				} else {
					compileHtml();
				}

				if (type === 'add') {
					setTimeout(function() {
						util.loadPlugin('build_dev');
					}, 500);
				}

				break;
```
配置文件啥的我自己去取我配置的文件，然后把gulpfile和util里的参数换了。

**Comment by littledu** [comment]
感谢反馈，两个问题已经修复。正在同步中...

配置文件 .tmtworkflowrc 有开放啊，你说的配置文件是？？？配置是支持项目化的，比如你截图里面的 .tmtworkflowrc 是在根目录下，那么，当项目(actvi 或 temp )下都没有 .tmtworkflowrc 时，是直接读取的全局，如果具体项目下有配置文件，则读取的是项目下的配置，达到不同项目不同配置。

插件则全部放在 _tasks/plugins 下面，只要不同配置调用不同的插件即可。

**Comment by ktangel** [comment]
问题来啦，.tmtworkflowrc在win下创建不方便的，你试下就知道了。会提示没有文件名哦。
```
var gulp = require('gulp');
var fs = require('fs');
var path = require('path');
var config = deep_require('config.json',2);

if (config) {
	deep_require('_tasks',2);
}

function deep_require(tasks_path, depps) {
	var deep = depps || 3;
	if (--deep < 0) {
		throw new Error('something wrong in require tasks!');
		return;
	}
	tasks_path = path.join('../', tasks_path);
	if (fs.existsSync(tasks_path)) {
		if (tasks_path === '_tasks') {
			require(tasks_path)(gulp, config);
		} else {
			return require(tasks_path);
		}
	} else {
		run_tasks(tasks_path);
	}
}
```
我刚作的小修改，既然你们已经是这样的可以忽略。
还是挺支持的，花了一段时间看你们源码，还是有些收获的，方便加Q交流不。

**Comment by littledu** [comment]
可以给我们提 pr 哦
这里返回的是相对路径，而且需要替换的目录肯定是在第一位，可以直接 replace(/src/, 'dev') ,所以可以直接把 src 替换，不用写很多哈

**Comment by ktangel** [comment]
之前想过 replace(/src/, 'dev')这样改，感觉不够严谨。。

**Comment by littledu** [comment]
正则替换这里只会替换第一个找到的，即使你后面文件名有 src 关键字，也不会替换，所以还好

**Comment by ktangel** [comment]
你只用正则改了img的，其它的都是字串。

**Comment by littledu** [comment]
呃。。。那等过两天我加个新功能一起更新一下吧
