### ISSUE TITLE
发布流程里的雪碧图问题

### ISSUE THREAD

**Issue by ktangel** [weixin/tmt-workflow#34]
因为我看这是开发过程把要合成雪碧图的图片放在slice里，发布生产时会合成雪碧图，那css里引用的类的话呢，也会自动定位图片替换背景position么？ 还是要遵循什么class的命名规范

**Comment by hzlzh** [comment]
CSS 调用背景图的时候会这样写 `../slice/xxx.png` 或者 `../img/xxx.png`。
其中，前者会自动进入雪碧图，并且补全合并后计算正确的 background-position 值，后者则不作任何操作。

via: https://github.com/weixin/tmt-workflow/wiki/%E2%92%8E-CSS-Sprite
