### ISSUE TITLE
lib-rem.less 小讨论

### ISSUE THREAD

**Issue by ktangel** [weixin/tmt-workflow#35]
lib-rem我看用css用了一些响应式的定义，它和用js里的ready+resize动态根据宽度改有哪些优缺点呢。

**Comment by hzlzh** [comment]
主要看使用场景：如果是响应式布局，类似 iPhone 5/6/6Plus 这种阶段性的变化，用 css + mediaquery 就好，也更快速。
如果是需要任何比例下都是等比缩放，则要用 js 来动态改变，可以参考另一个小 repo https://github.com/hzlzh/bigger.js
