### ISSUE TITLE
现在支持同时挂两个项目的dev进程么。

### ISSUE THREAD

**Issue by ktangel** [weixin/tmt-workflow#36]
dev模式下的web虚拟服务的网站根目录结构好像没有项目那一级，也就是同一时间是没办法两个项目挂着开发么？

**Comment by hzlzh** [comment]
支持，同时多个项目并行 dev 没有问题。
你可以发现预览地址是：`http://localhost:8080/html/TmTIndex.html` 类似这样，当你运行另一个项目时端口号会改变，如 `8081` `8082` 这样就不会冲突了。

同样 GUI App 里可以同时监听多个项目 via https://github.com/weixin/WeFlow#界面预览
