### ISSUE TITLE
雪碧图合并是在哪个方法 里呢，我的不知道为什么dist时图不合并。

### ISSUE THREAD

**Issue by ktangel** [weixin/tmt-workflow#43]

**Comment by littledu** [comment]
看看是不是你的写法不对，看看这里：
https://github.com/weixin/tmt-workflow/wiki/%E2%92%8E-CSS-Sprite

**Comment by ktangel** [comment]
看了一下，我是按这写法写的，Dev时会自动在CSS上加上宽度和高度，dist时也会加上，就是不合并。
![image](https://cloud.githubusercontent.com/assets/11548772/16227819/af4fe55c-37e5-11e6-8b6f-204b04ad8c09.png)
你看下我的目录

**Comment by ktangel** [comment]
找到原因了，原来是有些直接写的background:而不是background-image属性。 = V =
