### ISSUE TITLE
关于reversion解决方案的bug

### ISSUE THREAD

**Issue by xiewl** [weixin/tmt-workflow#45]
reversion解决方案发现一个bug。dist后href的几种地址方式。
![qq 20160622162305](https://cloud.githubusercontent.com/assets/15881722/16259580/ec627b02-3895-11e6-862a-9ef937b2c25e.png)
1、绝对地址没问题
2和3、项目内不存在的相对地址没问题
4和5、如图。

**Comment by hzlzh** [comment]
https://github.com/smysnk/gulp-rev-all 在相对路径和绝对路径上存在几个已知的问题，目前作者有几个 PR  还没合并，可以参考：
https://github.com/smysnk/gulp-rev-all/pull/146
https://github.com/smysnk/gulp-rev-all/issues/138
