### ISSUE TITLE
如何分别指定上传路径,因为目前的项目中,项目过于庞大

### ISSUE THREAD

**Issue by leolee2356** [weixin/tmt-workflow#46]
如图
|----js
  |---细分小项目
|----image
 |----细分小项目
如果能把weflow的改成这样呢

**Comment by littledu** [comment]
不是很明白，是一个项目，一部分要上传到一个地方？一部分要上传另一个地方？

**Comment by leolee2356** [comment]
对.基本上你理解的这个意思.

**Comment by hzlzh** [comment]
是否是项目太大，不想每次都全量覆盖部署，希望增量或变量发布？

**Comment by leolee2356** [comment]
@hzlzh  就是您说的增量发布的意思,我是菜鸟,表达的不太明确,给大家造成误解了
