### ISSUE TITLE
图片问题

### ISSUE THREAD

**Issue by renxj** [weixin/tmt-workflow#47]
很奇怪的一个问题，运行gulp build_dist第一次时正常，多次之后图片没有拷贝过来合并，望大神指点
![image](https://cloud.githubusercontent.com/assets/19201241/16295230/167387b6-3958-11e6-8eba-1ed1ba0ebec8.png)

**Comment by littledu** [comment]
是否开启了增量更新？ 查看 配置文件 `.tmtworkflowrc` 里面的 supportChange 字段

**Comment by renxj** [comment]
@littledu 嗯 开启了 不能开启是吧
