### ISSUE TITLE
最近遇到官网的目录结构不适合html文件放到html目录里，

### ISSUE THREAD

**Issue by ktangel** [weixin/tmt-workflow#53]
于是做了些修改，发现TmTIndex.js这个插件并没有引用配置里的目录，而是写死的html位置，导致之前就算改配置里的入口文件也没用，还在Dev里加入了posthtml的include插件，可以用标签方式导入别的html文件作为模板块，这样就更灵活组装头部底部和部分页面共用，它和别的插件最大区别就是不是用的注释标签，<include src="header.html"></include>而是这个自定标签，在gulp的时候它会被插件替换成src 批向的html里的内容，最重要的是它可以被不用的时候被注释！（其它注释型标签不能被注释）；
这些新的东西需要我push给你么？

**Comment by ktangel** [comment]
补充，watchHandler  里也没有对根目录是html文件的变化的这处情况作处理，于是会报错。

**Comment by littledu** [comment]
不是很明白。

`TmTIndex.js` 是我们用来列出目录下所有 html 文件的索引页，`tmt-workflow` 规定 `dev` 目录是开发目录，相应的资源目录也都是有相应的规定，所以写死也是可以的。

```javascript
          case 'html':
                if (type === 'removed') {
                    var tmp = file.replace('src', 'dev');
                    del([tmp]).then(function () {
                        util.loadPlugin('build_dev');
                    });
                } else {
                    compileHtml();
                }

                if (type === 'add') {
                    setTimeout(function () {
                        util.loadPlugin('build_dev');
                    }, 500);
                }

                break;
```

`watchHandler ` 是监听 html 目录下的 html 文件变动。

**Comment by ktangel** [comment]
就是如果我要把html文件目录结构放在根目录而不是html目录的话，就会有各种问题，而不是改改配置就行，改完后发现DEV模式里聊了dev.js里要改，然后插件里的你是写死，所以还是需要改插件里的，我只是提个建议，我改完了那些地方，然后现在可以兼容放在html目录里或是项目根目录，你这是否需要这个功能。。需要我就把改过的代码放上来，你看需要剪过去更新。

**Comment by littledu** [comment]
我们有规范要求我们 html 文件要放在 html 目录下，在一定的规范下可以更方便的开发，你们规范跟我们不一样，可以相应改成适合自己的。
