### ISSUE TITLE
 开启 新文件名 md5 功能后，html文件中的JS的引用不会加进去

### ISSUE THREAD

**Issue by ktangel** [weixin/tmt-workflow#55]
CSS和图片的文件链接会加上 md5。但JS并不会。

顺便抛个讨论问题：
这个功能的作用是为了生产版本的缓存更新，防止缓存对吧，
除了这种改文件名的，还有种是?+md5的方式来防止缓存，我个人常见得后者可以少生成很多新文件，只需要改动html中的引用链接就能达到目录，会好很多，不过你这里用到的rev-all插件要改源码的地方很多，还没有花时间去仔细查看怎么改。

**Comment by littledu** [comment]
好，我们来讲讲时间缀的缓存。

当我静态资源更新了后，所有引用这个静态资源的文件都要相应的变动，如：

```
a.css?v=1 -> a.css?v=2`
```

问题来了，我要发布，我是先发 css 还是 html，还是同时发，不管怎么样，他们之间总会有一个生效的时间差。

这时，用户访问就会有两种情况：

1.  html 先于 css ： 用户访问到的是新的页面，新的结构，发现资源也更新了，向服务器发起请求，但拉回来还是旧的样式，很好，新的结构没找到对应的样式，以结构错乱而告终;

2. css 先于 html:  用户访问页面，发现样式没更新，从缓存中取，嗯，页面正常，但这个是有缓存的情况，也就是老用户; 如果是新用户，就会发起请求，拿到的是新的样式，但结构还没更新，同样也要挂。

对于一个用户量庞大的公司来讲，时刻都有用户访问着你的产品，为了彻底解决这个问题，新文件的发布方式无疑是目前的最佳选择。每次更新先发资源，资源更新完了再发 html 等引用入口文件，则不会出现 `时间缀` 方式所带来的问题。

**Comment by ktangel** [comment]
嗯，有道理。。不改名的话就会存在覆盖先后和服务器缓存的问题，以实时性来说是新文件名发布会空错性好。。我这公司的网站用户少没考虑到这种情况，谢谢分享经验，get新知识了。

**Comment by ktangel** [comment]
另外，html 里js并不会加上md5的问题，有确认到么？

**Comment by ktangel** [comment]
还是js并不需要加md5?

**Comment by littledu** [comment]
是指在 html 中的外链 js 还是内嵌 js 中的引用？

**1. 外链 JS**

```html
<script src="../js/index.js"></script>
```

md5 后：

```html
<script src="../js/index.6b3a92ef.js"></script>
```

正常！

**2. 内嵌 JS**

```html
<script>
      var jsPath = '../js/index.js'; //这种也是能正常转换的
</script>
```

请详细说明一下你的使用方式

**Comment by ktangel** [comment]
就是外链。我自己去查看一下revall的文档看看吧。。谢谢啦。

**Comment by q27488** [comment]
js代码中引入img，img在md5后，js无法找到正确路径该怎么解决？ 如图：
![1](https://cloud.githubusercontent.com/assets/17950922/23845875/8fa66956-0805-11e7-9b7f-366127582929.png)

![2](https://cloud.githubusercontent.com/assets/17950922/23845894/a2245a48-0805-11e7-8354-7d0dbb6647f1.png)

**Comment by Jerret321** [comment]
用require ...
