### ISSUE TITLE
多雪碧图如何生成？

### ISSUE THREAD

**Issue by sjmlsxp** [weixin/tmt-workflow#56]
是否可以按目录生成多张雪碧图，比如slice/a生成sprite/a.png, slice/b生成sprite/b.png...

**Comment by hzlzh** [comment]
可以的，雪碧图支持多张出口。
用法是使用多个 `less` 出口，比如 `style-aaa.less` `style-bbb.less` 内引用的 `./slice/`  下的文件会分别生成 `style-aaa.png` `style-bbb.png`

另外，计划在下一版的 demo 中展示多张雪碧图的用法，多谢这个反馈。

**Comment by hzlzh** [comment]
Demo 已改版，增加了多张雪碧图出口的使用范例，参见：
https://weflow.io/demo/html/
https://weflow.io/demo/html/doc.html
