### ISSUE TITLE
npm install 安装失败，求解救/(ㄒoㄒ)/~~

### ISSUE THREAD

**Issue by sjmlsxp** [weixin/tmt-workflow#61]
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! node-lwip@0.1.3 install: `node prebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-lwip@0.1.3 install script 'node prebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-lwip package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node prebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-lwip
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-lwip
npm ERR! There is likely additional logging output above.

**Comment by littledu** [comment]
你是 node6，你拉一下分支，分支里面的版本已更新。node-lwip@0.2.1 才支持 node6+

**Comment by littledu** [comment]
主干已更新
