### ISSUE TITLE
node版本的咨询

### ISSUE THREAD

**Issue by epirus** [weixin/tmt-workflow#62]
我想问一下你们对node的版本有要求吗？可以写到文档里吗？

**Comment by hzlzh** [comment]
目前是 5.10.x （via https://github.com/weixin/tmt-workflow/blob/master/.travis.yml）
稍后我在文档里加一下，多谢反馈。

**Comment by littledu** [comment]
这两天会准备合并支持 node6+ 的分支，故此对 node 版本没什么要求。

**Comment by epirus** [comment]
我这边使用了node 6.3.1  安装，一直出现gyp err的问题，所以就问一下你们的版本~

**Comment by hzlzh** [comment]
新版 6+ 的分支：https://github.com/weixin/tmt-workflow/tree/1.5.3
你可以切换到 node 5.10.x 先用当前版本的工作流
