### ISSUE TITLE
默认生成的是less后缀的，可以给用户选择默认为scss的吗？

### ISSUE THREAD

**Issue by WriterLuo** [weixin/tmt-workflow#64]
默认生成的是less后缀的，可以给用户选择默认为scss的吗？或者说目前也就只能用户手动去更改为scss文件？

**Comment by littledu** [comment]
不用切换啊，你直接放 `.scss` 的文件，也是直接编译好，不需要配置

**Comment by WriterLuo** [comment]
明白了……我本意思是想，默认创建项目的时候，就是.scss。。。

**Comment by littledu** [comment]
tmt-workflow 项目是由用户自己放进去的啊，没有`创建项目`.
