### ISSUE TITLE
生成雪碧图的一点疑问

### ISSUE THREAD

**Issue by zhoulijie** [weixin/tmt-workflow#65]
#### 如下：

```
mod-menu.less
    .a{
        background-image:url('../slice/menu/a.png');
    }
    .b{
        background-image:url('../slice/menu/b.png');
    }
    .c{
        background-image:url('../slice/menu/c.png');
    }

style-index.less
    @import "mod-menu.less";
    .d{//...}
    .e{//...}
    .f{//...}
    
style-about.less
    @import "mod-menu.less";
    .ab{//...}
    .cd{//...}
    .ef{//...}

style-list.less
    @import "mod-menu.less";
    //此处省略1万行样式

```

#### run
`gulp build_dist`, `sprite`文件夹下，生成的雪碧图是这样的：

```
style-index.a8a9671a.png
style-about.a8a9671a.png
style-list.a8a9671a.png
```

#### 疑问
由于`style-index.less` `style-about.less` `style-list.less`，引用同一个`mod-menu.less`，最后生成了三张雪碧图，并且每一张雪碧图的内容都是一样的(只是名字不一样)。

我的问题是，由于引用的是同一个样式文件(mod-menu.less),所以生成的三张雪碧图的内容也是一样的。如果有20个或更多的样式文件引用`mod-menu.less`，同理会生成相应数量的，且内容一样的雪碧图。这样有点浪费资源，可否将相同内容的雪碧图，只生成一张，引用之？

**Comment by littledu** [comment]
我们的雪碧图生成是根据文件，一个文件生成对应的一张雪碧图，这是合理的。
不同文件都应该相互独立，不相互耦合。
你要的无非就是公用组件的提取，你可以把 mod-menu 改成 style-menu，既然是公用的，就提取出来作为单独的一个出口文件，但很多时候在需求里面都不会尽善尽美，你总会在具体项目里面覆盖公用的组件，或是公用的组件实际只用到一点点。
你觉得呢？

**Comment by zhoulijie** [comment]
@littledu  很感谢这么效率的解答。我当初所想，与您描述的大致相同（style-menu.less写成独立的一个出口文件）。但是遇到了一个问题，我并不想在每个html里，都有两个外链的css文件，所以把`style-menu.less` 看做一个模块文件，通过import的方式去引入。如按您所描述的，有什么办法可以解决上述几个问题(疑虑)？对`tmt-workflow`还不是太理解，有什么冒犯的地方还请谅解。

**Comment by littledu** [comment]
其实这个需要权衡，如果多个文件生成的雪碧图是只有一个，也就是说同时间被多个页面引用，那有一天其中一个文件添加了一个 icon ，即便我们能保证不影响其他文件，那其他页面是否又存在没必要的图片，是不是也觉得浪费？而我们现在的方式只是占用硬盘和服务器，页面加载的时候，所加载的那张雪碧图里面的内容则为我们页面所有的，对比另一种做法，一个是有冗余的小图片，浪费带宽，一个是重复的雪碧图，占用空间。
如果图片都能保证是公用的，那提出来变成两条样式也无不可，如果无法保证，那作为模块文件解藕则会更好。

**Comment by zhoulijie** [comment]
受教了！十分感谢！
