### ISSUE TITLE
rem方案的讨论

### ISSUE THREAD

**Issue by ktangel** [weixin/tmt-workflow#66]
因为我公司的美术统一出的效果图是1080x1920。我的方案是以1080效果图的50px作为基准1rem值。
然后通过js去动态计算手机上适配需要的缩放值:viewprot宽度 \* (50/1080)，然后设置到html样式里，好处是能适配iphone和绝大部分安卓手机。
我看你这个也需要js辅助，但是看着好像只是针对性的对iphone进行各种适配，并没有对安卓的适配？

**Comment by hzlzh** [comment]
工作流里的默认方案没有 JS 依赖，采用的是 Media Query 来做区段阶段性适配（支持 iPhone/iPad 和 Android 等设备），如果再引入一个根据屏幕宽度动态计算根节点 font-size 值的 JS 库就能实现完全的实时等比适配了。
至于 PC 也是一样的逻辑，你可以把你的基准值改成 20px:1rem 试试，如果用 50px 做基准值，对应的 lib-rem.less 和 px2rem root 参数都要一起修改定制。
