### ISSUE TITLE
项目附带示例 gulp build_dist 没有成功

### ISSUE THREAD

**Issue by biosrs** [weixin/tmt-workflow#68]
project-webpack目录下面gulp build_dist没有成功, 查看了下,index.html引用了../js/lib/prism.js, 但是在gulp build_dev的时候prism.js跑到上一层目录下了,js目录下面也没有lib目录了,导致build_dist的时候找不到从而失败.

**Comment by littledu** [comment]
谢谢反馈，已修复。

目前 tmt-workflow 支持两种 JS 处理方式。

1. 没有 webpack, 则用 `gulp-usemin` 通过注释形式进行 js 合并
2. 有 webpack，则希望按 webpack 的方式走，用模块引用方式，出口自定义

两种方式选其一， project-webpack 的示例错误的引用了 `gulp-usemin`，所以报错了。

**Comment by biosrs** [comment]
hi, 没有改好啊, 你试试, 只要lib目录没有,最后还是引用不到啊, 你看是不是'prism': './js/lib/prism.js' 改成'lib/prism': './js/lib/prism.js'

**Comment by littledu** [comment]
谢谢 @biosrs，已经重新修改，再次确认无误后重新发布了。
