### ISSUE TITLE
WeFlow好像只能默认生成 style-index.less 文件，能否全局设置成默认使用sass啊

### ISSUE THREAD

**Issue by zhengshuai1001** [weixin/tmt-workflow#71]

**Comment by littledu** [comment]
less 和 sass 都支持，不需要配置，你换个 scss 文件试试就知道了

**Comment by zhengshuai1001** [comment]
嗯，我只是觉得不能提前设置成sass ，不是很方便:grin:

**Comment by littledu** [comment]
你说的是新建项目时的模板，我在另一个 issues 回答你了

**Comment by zhengshuai1001** [comment]
非常感谢:grin:。那我说的报错时桌面弹窗的功能能开发么？

**Comment by littledu** [comment]
可以是可以，但报错了自然就会没有效果，这个样子不就是提醒了你有问题了么？这个时候你再看一下 log 就知道哪里写错了

**Comment by zhengshuai1001** [comment]
好吧，我之前用的Koala，他能报错弹窗，看样子被它惯坏了。。。

**Comment by littledu** [comment]
我觉得我们下一版应该也可以。

**Comment by zhengshuai1001** [comment]
谢谢
