### ISSUE TITLE
Failed at the node-lwip@0.1.3 install script 'node prebuild'

### ISSUE THREAD

**Issue by ryangun** [weixin/tmt-workflow#73]
npm WARN project@0.0.1 No description
npm WARN project@0.0.1 No repository field.
npm WARN project@0.0.1 No license field.
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/ganzhonghuan/.nvm/versions/node/v6.3.0/bin/node" "/Users/ganzhonghuan/.nvm/versions/node/v6.3.0/bin/npm" "install"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! node-lwip@0.1.3 install: `node prebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-lwip@0.1.3 install script 'node prebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-lwip package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node prebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-lwip
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-lwip
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ganzhonghuan/ryangun/www/tmt-workflow/npm-debug.log

**Comment by ryangun** [comment]
安装依赖的时候在这里报错了，请问怎么解决啊？

**Comment by ryangun** [comment]
用yo workflow初始化的方式再npm install就会这样；而直接下载你们的那个tmt-workflow，再npm install就没有问题。

**Comment by littledu** [comment]
yo 的忘了同步更新。。。。。。sorry

**Comment by littledu** [comment]
已修复

**Comment by ryangun** [comment]
@littledu 赞！
