### ISSUE TITLE
MAC还是不能用，MAC还是不能用！

### ISSUE THREAD

**Issue by evenle** [weixin/tmt-workflow#76]
工作路径一直显示是  **/Users/Apple/Workspace/Projects/**
感觉是你们获取和设置工作路径的原因，根本用不了， 从10.9到10.11 到MACOS，都升级了，都用不了，工作路径永远不对。家里的电脑又可以用！！！！帮忙查一下这个问题吧！

**Comment by hzlzh** [comment]
你提的反馈是针对  WeFlow 使用而言的吧？我们没有设置这个工作目录。
你试一下重新安装，删除 demo。

**Comment by hzlzh** [comment]
/Users/Apple/ 根据你之前反馈的路径来看，这个用户名是 Apple，这个字段在我们的源码中是没有的，你本地的用户名不是 Apple 吧？

**Comment by littledu** [comment]
WeFlow 默认的工作路径：
Mac: 在默认的用户目录下，如: `/Users/littledu/WeFlow_workspace`
Win:  在桌面，如 `C:\\Desktop\\WeFlow_workspace`

你这个工作路径 Workspace 是改过么

**Comment by evenle** [comment]
改了啊，改了没有用

**Comment by littledu** [comment]
你家里的电脑可以，公司的又不可以，如果是同样的配置，还真是猜不出来哪里问题。

**Comment by evenle** [comment]
电脑配置不一样，公司是MAC MINI ,不能用，家里是MACBOOK，可以用，系统都一样

**Comment by littledu** [comment]
只是硬件不一样。。。。。
