### ISSUE TITLE
Press <space> to select

### ISSUE THREAD

**Issue by xcsweb** [weixin/tmt-workflow#77]
我使用yeoman的安装方法，在window环境下用的是git bash，但是点击空格键之后就是选择不了，怎么解决

**Comment by littledu** [comment]
倒是第一次反馈说 yeoman 空格选择不了，我这里无法复现，你重新试试看。

**Comment by xcsweb** [comment]
我去yeoman向他们提问之后，他们说用cmd可以,但是git bash为什么不行我就不清楚了
