### ISSUE TITLE
发布后的雪碧图会放到sprite下，但是朋友圈广告审核那里不让过呀，说不能有sprite目录

### ISSUE THREAD

**Issue by anjorweb** [weixin/tmt-workflow#85]
如题，这个不是朋友圈广告推荐的工具么，为啥还会出现这个问题呢

**Comment by hzlzh** [comment]
应该没这限制吧，我问一下广告的同事

**Comment by anjorweb** [comment]
好的，帮忙问下哦~谢谢啦

**Comment by bammoo** [comment]
@anjorweb 谢谢反馈，已在解决中

**Comment by anjorweb** [comment]
嗯呢，我用的是WeFlow工具~谢谢各位

**Comment by anjorweb** [comment]
谢谢各位啦，对了，我用的是WeFlow工具

**Comment by whuhenrylee** [comment]
目前已经支持sprite目录的提交

**Comment by anjorweb** [comment]
好滴~谢谢咯，也就是说dist.zip里可以出现sprite目录啦，且审核不会因为这个卡住哈~

**Comment by hzlzh** [comment]
@anjorweb 问题已经解决了吧，可以 close 了
