### ISSUE TITLE
css 压缩后乱加样式，导致图片位移

### ISSUE THREAD

**Issue by w1997** [weixin/tmt-workflow#87]
![image](https://cloud.githubusercontent.com/assets/16370092/22725671/d8796950-ee09-11e6-95e4-119864795fd8.png)

**Comment by littledu** [comment]
把相关代码放上来看看？

**Comment by w1997** [comment]
![qq 20170208171948](https://cloud.githubusercontent.com/assets/16370092/22730767/44baf548-ee23-11e6-9d25-7c995050a99e.png)

如图，开发的时候没有写width:640px;  编译过后多了样式width:640px;

**Comment by w1997** [comment]
问一下，修复了没有。

**Comment by hzlzh** [comment]
如果宽高没写会给你添加对应属性，你试一下写全宽高。

**Comment by w1997** [comment]
可以了。
