### ISSUE TITLE
bash: yo: command not found

### ISSUE THREAD

**Issue by NicholasNC** [weixin/tmt-workflow#89]
```
npm install -g generator-workflow
yo workflow
```

在执行 `yo workflow` 就报错，如题找不到改命令。

环境：
1. nodejs `v7.3.0`
1. npm  `3.10.10`
1. 系统 win10 64位
1. 使用Git bash执行命令

**Comment by hzlzh** [comment]
看一下生成器是不是没有安装完全，试一下 cnpm
cnpm install -g generator-workflow
https://npm.taobao.org/
