### ISSUE TITLE
node 7 下安装依赖报错

### ISSUE THREAD

**Issue by ganyusheng520** [weixin/tmt-workflow#92]
node v7.7.4
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! node-lwip@0.1.3 install: `node prebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-lwip@0.1.3 install script 'node prebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-lwip package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node prebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-lwip
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-lwip
npm ERR! There is likely additional logging output above.

**Comment by hzlzh** [comment]
尝试一下  https://npm.taobao.org/ 安装依赖
