### ISSUE TITLE
怎么设置px2rem 基准值

### ISSUE THREAD

**Issue by 15697289437** [weixin/tmt-workflow#93]
怎么设置px2rem 基准值，默认是20在哪里设置啊，样式中设置html font-size也无效

**Comment by hzlzh** [comment]
另外 HTML 里 rem 的触发方式是：<html lang="zh-CN" data-rem="375">

https://github.com/weixin/tmt-workflow/blob/master/_tasks/TaskBuildDist.js#L78
https://github.com/weixin/tmt-workflow/blob/master/_tasks/TaskBuildDist.js#L185

**Comment by soyaine** [comment]
现在代码位置在：
https://github.com/Tencent/tmt-workflow/blob/master/_tasks/TaskBuildDist.js#L92
https://github.com/Tencent/tmt-workflow/blob/master/_tasks/TaskBuildDist.js#L207
