### ISSUE TITLE
为什么无法引用bootstrap，路径无法识别

### ISSUE THREAD

**Issue by CodeMagic6** [weixin/tmt-workflow#95]
GET http://localhost:3000/src/css/bootstrap.min.css 
GET http://localhost:3000/src/img/3F92BDBF-0208-4522-8B2D-305D9A0D3F39@1x.png 404 (Not Found)
GET http://localhost:3000/src/bootstrap.min.js 
GET http://localhost:3000/html/... 404 (Not Found)

**Comment by littledu** [comment]
路径错误
