### ISSUE TITLE
如何增加自定义文件和文件夹的编译

### ISSUE THREAD

**Issue by CodeMagic6** [weixin/tmt-workflow#96]
比如我想在src下增加一个js的文件夹，里面存放js，在src下引入一个jquery包，如何保证他们同时都会被编译至dev文件夹下

**Comment by sandmanman** [comment]
@CodeMagic6 你解决了？修改task文件吗？我增加了fonts文件夹，但是dist报错...

**Comment by littledu** [comment]
@sandmanman 你可以把 fonts 文件夹放进 media 目录

**Comment by sandmanman** [comment]
@littledu 按照copyMedia() 来写 copyFonts()，是不是也不行，执行build_dist报错copyFonts，还是需要其他的配置？谢谢。
