### ISSUE TITLE
dist打包同一个CSS文件内的less和CSS文件失败~同一项目dev目录成功

### ISSUE THREAD

**Issue by CGerAJ** [weixin/tmt-workflow#97]
dist 目录不能输出合并文件 只能高输出LESS的编译打包文件 不能将目录内的CSS和less一起打包 
//编译 less
    function compileLess() {
        return gulp.src(paths.src.less)
            .pipe(less({relativeUrls: true}))
            .pipe(concat('minmax.css'))
            .pipe(rename({ suffix: '.min' }))
            .pipe(minifycss())
            .pipe(lazyImageCSS({imagePath: lazyDir}))
            .pipe(tmtsprite({margin: 4}))
            .pipe(gulpif('*.png', gulp.dest(paths.tmp.sprite), gulp.dest(paths.tmp.css)));
    }

//编译 less
dev目录打包完全正常  直接合并成一个压缩文件
    function compileLess() {
        return gulp.src(paths.src.less)
            .pipe(less({relativeUrls: true}))
            .pipe(concat('minmax.css'))
            .pipe(rename({ suffix: '.min' }))
            .pipe(minifycss())
            .on('error', function (error) {
                console.log(error.message);
            })
            .pipe(lazyImageCSS({imagePath: lazyDir}))
            .pipe(gulp.dest(paths.dev.css))
            .on('data', function () {
            })
            .on('end', reloadHandler)
    }
我该如何使用正确的配置 谢谢~

**Comment by littledu** [comment]
从你修改的配置上看，两个流程之间只有雪碧图合并的区别，雪碧图合并有相应的规则，看是否是你合并的css里面有不符合规则有触发了合并条件导致？

**Comment by CGerAJ** [comment]
谢谢提醒~ 目前在开发目录   重新审视下gulpfile文件定制新的dist部署环境
